baseurl = "/"
languageCode = "en"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # OS theme is default when not provided, but you can force it to "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true



[languages]


  [languages.en]

    contentDir = 'content/en'
    languageName = 'English'
    weight = 10

    [languages.en.params]
        title = "Threat Anatomy Blog"
        subtitle = "Dissecting threats"
        keywords = ""
        copyright = ""
        menuMore = "Show more"
        writtenBy = "Written by"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
        minuteReadingTime = "min read"
        dateFormatSingle = "2006-01-02"
        dateFormatList = "2006-01-02"
        # leave empty to disable, enter display text to enable
        # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Threat Anatomy Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      #[[languages.en.menu.main]]
       # identifier = "about"
       # name = "About"
       # url = "/en/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/en/contact"
      #[[languages.en.menu.main]]
       # identifier = "showcase"
        #name = "Showcase"
        #url = "/en/showcase"

  [languages.es]

    contentDir = 'content/es'
    languageName = 'Spanish'
    weight = 20

    [languages.es.params]
        title = "Threat Anatomy Blog"
        subtitle = "Diseccionando amenazas"
        keywords = ""
        copyright = ""
        menuMore = "Ver m치s"
        writtenBy = "Escrito por"
        readMore = "Leer m치s"
        readOtherPosts = "Leer otras publicaciones"
        newerPosts = "Publicaciones m치s nuevas"
        olderPosts = "Publicaciones m치s antiguas"
        minuteReadingTime = "min de lectura"
        dateFormatSingle = "2006-01-02"
        dateFormatList = "2006-01-02"
        # leave empty to disable, enter display text to enable
        # lastModDisplay = ""

    [languages.es.params.logo]
      logoText = "Threat Anatomy Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.es.menu]
      #[[languages.es.menu.main]]
       # identifier = "about"
       # name = "Acerca de"
       # url = "/es/about"
      [[languages.es.menu.main]]
        identifier = "contact"
        name = "Contacto"
        url = "/es/contact"
     # [[languages.es.menu.main]]
      #  identifier = "showcase"
       # name = "Showcase"
        #url = "/es/showcase"

